[package]
name = "string-shortener"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
kdam = "0.3.0"
unic = "0.9.0"
unic-char-range = "0.9.0"
unidecode = "0.3.0"
